resolver: lts-11.13

packages:
- '.'
- location:
    git: https://github.com/haskell-distributed/distributed-process-systest.git
    commit: b4a6b646adb6c81725ddac4babcfc21b86944d98
  extra-dep: true

extra-deps:
- network-transport-inmemory-0.5.1  # snapshot 0.5.2 in lts-7.18
- distributed-process-0.7.4
- rematch-0.2.0.0
- network-transport-0.4.4.0         # missing snapshot
- network-transport-tcp-0.5.1       # missing snapshot
- exceptions-0.10.0
